### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/multi-factor-auth#1]
This list details what remains to be done to reach MVP:

- [x] Create the needed models and migrations
- [x] Create a middleware
- [x] Create a Controller that utilizes a trait such that the trait methods can be overridden by the end-user.
- [x] Create routes. Don't force the routes presence. That is, Have a way to disable them.
- [x] Create config files
- [x] Create a default notification
- [x] Create views (index and code entry)

**Comment by almasaeed2010** [comment]
Done
